const Menu = [{
    id:1,
    image:"images/1.jpg",
    name :"maggi",
    category:"breakfast",
    price:24,
    description:"hhhjjhjghhg",
},
{
    id:2,
    image:"images/2.jpg",
    name :"maggi",
    category:"lunch",
    price:24,
    description:"hhhjjhjghhg",
},
{
    id:3,
    image:"images/3.jpg",
    name :"maggi",
    category:"evening",
    price:24,
    description:"hhhjjhjghhg",
},
{
    id:4,
    image:"images/4.jpg",
    name :"maggi",
    category:"dinner",
    price:24,
    description:"hhhjjhjghhg",
},
{
    id:5,
    image:"images/5.jpg",
    name :"breakfast",
    category:"lunch",
    price:24,
    description:"hhhjjhjghhg",
},
{
    id:6,
    image:"images/6.jpg",
    name :"maggi",
    category:"breakfast",
    price:24,
    description:"hhhjjhjghhg",
},
];
export default Menu;